# Generated by Django 2.1.3 on 2019-01-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='agree',
            field=models.CharField(default='0', max_length=2),
        ),
    ]
