# Generated by Django 2.1.3 on 2019-01-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_profile_agree'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='agree',
        ),
        migrations.AddField(
            model_name='profile',
            name='coderesv',
            field=models.CharField(default='null', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='codesent',
            field=models.CharField(default='null', max_length=10),
        ),
    ]
