# Generated by Django 2.1.3 on 2019-01-06 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190106_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('codesent', models.CharField(default='null', max_length=10)),
                ('coderesv', models.CharField(default='null', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='coderesv',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='codesent',
        ),
    ]
