# Generated by Django 2.1.3 on 2019-01-07 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postpick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpick',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
    ]
