# Generated by Django 2.1.3 on 2019-01-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190107_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postpick',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='post_pics'),
        ),
        migrations.DeleteModel(
            name='PostPick',
        ),
    ]
