# Generated by Django 2.1.3 on 2019-01-07 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190107_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpick',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
