# Generated by Django 2.1.3 on 2019-01-07 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postpicks',
            old_name='user',
            new_name='userblog',
        ),
    ]
