# Generated by Django 2.1.3 on 2019-01-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190107_2251'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostPicks',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='post_pics'),
        ),
    ]
