# Generated by Django 2.1.3 on 2019-01-08 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20190107_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='showpost',
            field=models.CharField(default=1, max_length=2),
        ),
    ]
