# Generated by Django 2.1.3 on 2019-01-10 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_profile_college'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='college',
        ),
        migrations.AddField(
            model_name='post',
            name='college',
            field=models.CharField(default='GEC Thrissur', max_length=100),
        ),
    ]
