# Generated by Django 2.1.3 on 2019-01-10 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20190110_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='college',
            field=models.CharField(default='GEC Thrissur', max_length=100),
        ),
    ]
