# Generated by Django 2.1.3 on 2019-01-10 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_profile_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mobileno',
            field=models.CharField(default='null', max_length=11),
        ),
        migrations.AddField(
            model_name='profile',
            name='mobileno',
            field=models.CharField(default='null', max_length=11),
        ),
    ]
