# Generated by Django 2.1.3 on 2019-01-10 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20190110_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobileno',
            field=models.CharField(default='+91 XXXX XXX XXX', max_length=11),
        ),
    ]
