# Generated by Django 2.1.3 on 2019-01-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20190110_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tokens',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='tokens',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobileno',
            field=models.CharField(default='+91 XXXXXXXXXX', max_length=17),
        ),
    ]
