# Generated by Django 2.1.3 on 2019-01-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20190115_2241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tokens',
        ),
        migrations.AlterField(
            model_name='post',
            name='tokens',
            field=models.CharField(default=100, max_length=100),
        ),
    ]
