# Generated by Django 2.1.3 on 2019-01-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20190115_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tokenbyuser',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='tokens',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
