# Generated by Django 2.1.3 on 2019-01-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20190116_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tokenacc',
            field=models.CharField(default=1000, max_length=100),
        ),
    ]
