# Generated by Django 2.1.3 on 2019-01-20 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_post_bookeditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='nameu',
            field=models.CharField(default='No Name', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='nameu',
            field=models.CharField(default='No Name', max_length=100),
        ),
    ]
