# Generated by Django 2.1.3 on 2019-01-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20190122_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='msgscount',
            field=models.IntegerField(default=0),
        ),
    ]
