# Generated by Django 2.1.3 on 2019-01-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_chat_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='seen',
            field=models.IntegerField(default=0),
        ),
    ]
