# Generated by Django 2.1.3 on 2019-01-22 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_chat_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='seen',
        ),
    ]
