# Generated by Django 2.1.3 on 2019-01-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_remove_chat_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='showmsg',
            field=models.IntegerField(default=1),
        ),
    ]
