# Generated by Django 2.1.7 on 2019-02-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_chat_showmsg'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=10)),
                ('msg', models.TextField()),
            ],
        ),
    ]
