# Generated by Django 2.1.7 on 2019-02-28 21:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_feedbackdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackdb',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
