# Generated by Django 2.1.7 on 2019-02-28 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_feedbackdb_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackdb',
            name='user',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
