# Generated by Django 2.1.7 on 2019-02-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_feedbackdb_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackdb',
            name='admincomment',
            field=models.TextField(default='null'),
        ),
    ]
