# Generated by Django 2.1.7 on 2019-03-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_feedbackdb_admincomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='profile',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Profile'),
        ),
    ]
